### ISSUE TITLE
Package installation problems from Github

### ISSUE THREAD

**Issue by bartling** [UrbanCCD-UChicago/aot-client-r#3]
When attempting to install with devtools, I get this error:

> devtools::install_github("UbranCCD-UChicago/aot-client-r")
Error: HTTP error 404.
  Not Found
  Rate limit remaining: 53/60
  Rate limit reset at: 2018-12-20 20:46:38 UTC

When attempting to install with `githubinstall` package I also get an error:

> githubinstall("aot-client-r")
Suggestion:
  adjust/api-client-r  an R client for the KPI service https://docs.adjust.com/en/kpi-service/
Do you want to install the package (Y/n)?  n
cancelled by user
Warning message:
In fread(download_url, sep = "\t", header = FALSE, stringsAsFactors = FALSE,  :
  Found and resolved improper quoting out-of-sample. First healed line 4848: <<Puriney	honfleuR	"Evening, honfleuR" by Seurat>>. If the fields are not quoted (e.g. field separator does not appear within any field), try quote="" to avoid this warning.

**Comment by TroyHernandez** [comment]
Try using "Urban" in the command instead of "Ubran" :)

**Comment by vforgione** [comment]
Fixed with #7 thanks to @TroyHernandez
